name: Notify Discord on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord PR Notification
        uses: Ilshidur/action-discord@master
        with:
          args: "🛎️ Nuevo PR:\n${{ github.event.pull_request.title }} por ${{ github.event.pull_request.user.login }}\n<${{ github.event.pull_request.html_url }}>"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_FRONTEND }}
